// <auto-generated />
namespace Sdk.Ef.Repro.Lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Temp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("Sdk.Ef.Repro.Lib.Migrations.201808021435464_Temp", typeof(Temp).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "201808021435464_Temp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
